if(EXISTS "/home/fxh/Computer-Network/Lab2/lab2-rtp-Naivexc/Lab2-RTP-Test/rtp_test_all[1]_tests.cmake")
  include("/home/fxh/Computer-Network/Lab2/lab2-rtp-Naivexc/Lab2-RTP-Test/rtp_test_all[1]_tests.cmake")
else()
  add_test(rtp_test_all_NOT_BUILT rtp_test_all_NOT_BUILT)
endif()
